# -*- coding: utf-8 -*-
"""SDA_Practical3_29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPDB00cnwzAX3cuEHPpRyEqp8p06MhM3
"""

# Step 1: Import Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("heart.csv")

print("Dataset Shape:", df.shape)
print(df.head())

le = LabelEncoder()

df['Sex'] = le.fit_transform(df['Sex'])
df['ChestPainType'] = le.fit_transform(df['ChestPainType'])
df['RestingECG'] = le.fit_transform(df['RestingECG'])
df['ExerciseAngina'] = le.fit_transform(df['ExerciseAngina'])
df['ST_Slope'] = le.fit_transform(df['ST_Slope'])

X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)



# Decision Tree Model


dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# Prediction
dt_train_pred = dt_model.predict(X_train)
dt_test_pred = dt_model.predict(X_test)

# Accuracy
dt_train_acc = accuracy_score(y_train, dt_train_pred)
dt_test_acc = accuracy_score(y_test, dt_test_pred)

print("\nDecision Tree Results")
print("Training Accuracy:", dt_train_acc)
print("Testing Accuracy:", dt_test_acc)

# Random Forest Model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Prediction
rf_train_pred = rf_model.predict(X_train)
rf_test_pred = rf_model.predict(X_test)

# Accuracy
rf_train_acc = accuracy_score(y_train, rf_train_pred)
rf_test_acc = accuracy_score(y_test, rf_test_pred)

print("\nRandom Forest Results")
print("Training Accuracy:", rf_train_acc)
print("Testing Accuracy:", rf_test_acc)

print("\nModel Comparison")
print("Decision Tree Test Accuracy:", dt_test_acc)
print("Random Forest Test Accuracy:", rf_test_acc)

# Classification Report
print("\nRandom Forest Classification Report:")
print(classification_report(y_test, rf_test_pred))

