# -*- coding: utf-8 -*-
"""SDA_Practical2_29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15r0EZc_PCqrnm-UqshMA9xtDicljPzqw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Create a Simple Student Dataset
df = pd.read_csv("StudentsPerformance.csv")

print("First 5 Records")
print(df.head())

encoder = LabelEncoder()

df["gender"] = encoder.fit_transform(df["gender"])
df["race/ethnicity"] = encoder.fit_transform(df["race/ethnicity"])
df["parental level of education"] = encoder.fit_transform(df["parental level of education"])
df["lunch"] = encoder.fit_transform(df["lunch"])
df["test preparation course"] = encoder.fit_transform(df["test preparation course"])

#Create Binary Column for Logistic Regression

df["pass"] = (df["math score"] >= 40).astype(int)

print("\nProcessed Dataset")
print(df.head())

"""# Linear Regression

"""

# Goal-Predict math Score


print("\n----- Linear Regression -----")

# Features and Target
X = df[["reading score", "writing score"]]
y = df["math score"]

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model Creation
model_lr = LinearRegression()

# Model Training
model_lr.fit(X_train, y_train)

# Prediction
y_pred = model_lr.predict(X_test)

# Evaluation
mse = mean_squared_error(y_test, y_pred)

print("Predicted Math Scores:", y_pred[:10])
print("Mean Squared Error:", mse)


# Visualization
plt.scatter(df["reading score"], df["math score"])
plt.xlabel("Reading Score")
plt.ylabel("Math Score")
plt.title("Reading Score vs Math Score")
plt.show()



"""# Logistic Regression

"""

# Goal → Predict Pass / Fail


print("\n----- Logistic Regression -----")

# Features and Target
X = df[["reading score", "writing score"]]
y = df["pass"]

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model Creation
model_log = LogisticRegression()

# Model Training
model_log.fit(X_train, y_train)

# Prediction
y_pred = model_log.predict(X_test)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Predicted Classes:", y_pred[:10])
print("Accuracy:", accuracy)

print("Confusion Matrix:")
print(cm)

